- include_tasks: ../../common/tasks/include_package_vars.yaml

- name: install
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts["distribution_major_version"] == "8"
  ansible.builtin.yum:
    disable_gpg_check: yes
    name:
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v26.2.1/erlang-26.2.1-1.el8.x86_64.rpm
      - https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.12.12/rabbitmq-server-3.12.12-1.el8.noarch.rpm
