global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "victoriametrics-main"
    static_configs:
      - targets:
          - "victoriametrics-main:9999"
  - job_name: "victoriametrics-vmagent"
    static_configs:
      - targets:
          - "victoriametrics-vmagent:8429"
