- name: Put neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify:
    - Restart neutron-server

- name: Put ml2_conf.ini
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify:
    - Restart neutron-server

- name: Sync DB
  shell: |
    {{ neutron_venv }}/bin/neutron-db-manage --config-file /etc/neutron/neutron.conf \
      --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

- name: Start neutron-server
  service:
    name: neutron-server
    state: started
