- name: install
  ansible.builtin.shell: |
    python3 -m venv /opt/workstation --system-site-packages

- name: install
  ansible.builtin.copy:
    src: files/requirements.txt
    dest: /opt/workstation/requirements.txt

- name: install
  ansible.builtin.shell: |
    /opt/workstation/bin/pip install pip --upgrade
    /opt/workstation/bin/pip install -r /opt/workstation/requirements.txt
    test -e /usr/bin/openstack || ln -s /opt/workstation/bin/openstack /usr/bin/openstack

- name: instlal kubectl
  ansible.builtin.shell: |
    if ! command kubectl; then
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/bin/kubectl
      rm kubectl
    fi

- name: instlal helm
  ansible.builtin.shell: |
    if ! command helm; then
      curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz
      tar xf helm.tar.gz
      install -o root -g root -m 0755 linux-amd64/helm /usr/bin/helm
      rm -rf linux-amd64
      rm helm.tar.gz

      helm plugin install https://github.com/databus23/helm-diff
    fi
