- name: Put local_settings.py
  template:
    src: local_settings.py.j2
    dest: "{{ horizon_venv }}/share/horizon/openstack_dashboard/local/local_settings.py"
  register: local_settings_py

- name: Start horizon
  shell: |
    set -e

    systemctl reset-failed horizon || echo 'ignored'
    systemctl status horizon || systemd-run \
      -p WorkingDirectory={{ horizon_venv }}/share/horizon \
      --unit horizon -- \
      {{ horizon_venv }}/bin/python manage.py runserver 0.0.0.0:80

- name: Restart horizon
  when: local_settings_py.changed
  shell: |
    set -e

    systemctl restart horizon
