- name: Set helm_release_values
  vars:
    self_values: "{{ hostvars[inventory_hostname] }}"
    extra_values:
      neutron_conf: "{{ lookup('template', './neutron.conf.j2') }}"
      neutron_api_paste_ini: "{{ lookup('template', './api-paste.ini.j2') }}"
      secret_neutron_conf: "{{ lookup('template', './secret/neutron.conf.j2') }}"
      ml2_conf_ini: "{{ lookup('template', './ml2_conf.ini.j2') }}"
  ansible.builtin.set_fact:
    helm_release_values: "{{ self_values | combine(extra_values) }}"

- name: Deploy neutron
  kubernetes.core.helm:
    name: neutron
    release_namespace: neutron
    chart_ref: /etc/ansible/collections/ansible_collections/labo/openstack_bobcat/charts/neutron
    release_values: "{{ helm_release_values }}"
    create_namespace: true
    atomic: true
    timeout: 1m
