groups:
- name: myjob
  rules:
  - alert: check1
    expr: check1{job="myjob"} > 0
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: check1 alert summary
  - alert: check2
    expr: check2{job="myjob"} > 0
    for: 5s
    labels:
      severity: warning
    annotations:
      summary: check2 alert summary
  - alert: check3
    expr: check3{job="myjob"} > 0
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: check3 alert summary

- name: pushgateway
  rules:
  - alert: check_pusher1
    expr: check_pusher1{job="federate-pushgateway"} > 0
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: check_pusher1 alert summary
  - alert: check_pusher2
    expr: check_pusher2{job="federate-pushgateway"} > 0
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: check_pusher2 alert summary
