name: nginx

services:
  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/tls.conf:/etc/nginx/conf.d/tls.conf
      - /etc/labo/tls-assets/localhost.test/server.pem:/etc/nginx/ssl/server.pem
      - /etc/labo/tls-assets/localhost.test/server-key.pem:/etc/nginx/ssl/server-key.pem
