- name: Gather subset
  ansible.builtin.setup:
    gather_subset:
      - distribution

- name: Install
  ansible.builtin.include_tasks: "install_{{ ansible_facts['distribution'] | lower }}{{ ansible_facts['distribution_major_version'] }}.yml"

- name: Setup on docker
  ansible.builtin.include_tasks: setup_docker.yml
