- name: Start postgres
  community.docker.docker_container:
    name: postgres
    image: postgres
    network_mode: host
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "/var/lib/docker-postgres:/var/lib/postgresql/data:rw"
