imports:
  - /etc/ansible/host_vars/localhost.yaml

kind: VMImage
name: rocky9-custom
spec:
  from: local/rocky9
  steps:
    - file:
        src: files/system/labo-init.service
        dst: /etc/systemd/system/labo-init.service
    - file:
        src: files/bin
        dst: /opt/labo/bin
    - cmd: rm -rf /etc/resolv.conf
    - file:
        src: files/etc/resolv.conf
        dst: /etc/resolv.conf
    - file:
        src: files/etc/fio.ini
        dst: /etc/fio.ini
    - cmd: systemctl enable labo-init
    - cmd: yum remove -y cloud-init
    - cmd: yum install -y epel-release
    - cmd: yum install -y fio dnsmasq tcpdump python3 python3-pip
    - cmd: pip install --upgrade pip
    - cmd: export LANG=C.UTF-8; export LC_ALL=en_US.UTF-8; pip install ansible
    - cmd: sed -i  's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config
    # 80-net-setup-link.rules があると、udevによって自動でifcfg-eth0を生成してしまうため削除する
    # デフォルトだとdhcpが利用されてしまうため、dhcpがタイムアウトで失敗するまで待たされてしまう
    - cmd: rm -rf /lib/udev/rules.d/80-net-setup-link.rules
    # network-scripts/ifcfg-eth0(anacondaで作成された?)が残ってるので削除してく
    - cmd: rm -rf /etc/sysconfig/network-scripts/ifcfg-eth0
    - cmd: systemctl disable NetworkManager
