keystone_data_projects:
  - name: service
    domain: default

keystone_data_users:
  - name: glance
    password: glancepass
    domain: default
    roles:
      - role: admin
        project: service
  - name: placement
    password: placementpass
    domain: default
    roles:
      - role: admin
        project: service
  - name: nova
    password: novapass
    domain: default
    roles:
      - role: admin
        project: service
  - name: neutron
    password: neutronpass
    domain: default
    roles:
      - role: admin
        project: service

keystone_data_services:
  - name: glance
    type: image
    description: OpenStack Image Service
  - name: nova
    type: compute
    description: OpenStack Compute Service
  - name: placement
    type: placement
    description: OpenStack Placement Service
  - name: neutron
    type: network
    description: OpenStack Network Service

keystone_data_region_endpoints:
  - region: playground
    services:
      - service: keystone
        endpoints:
          - interface: public
            url: "http://ctl01:5000/v3/"
          - interface: internal
            url: "http://ctl01:5000/v3/"
          - interface: admin
            url: "http://ctl01:5000/v3/"
      - service: glance
        endpoints:
          - interface: public
            url: http://ctl01:9292
          - interface: internal
            url: http://ctl01:9292
          - interface: admin
            url: http://ctl01:9292
      - service: nova
        endpoints:
          - interface: public
            url: http://ctl01:8774/v2.1
          - interface: internal
            url: http://ctl01:8774/v2.1
          - interface: admin
            url: http://ctl01:8774/v2.1
      - service: placement
        endpoints:
          - interface: public
            url: http://ctl01:8778
          - interface: internal
            url: http://ctl01:8778
          - interface: admin
            url: http://ctl01:8778
      - service: neutron
        endpoints:
          - interface: public
            url: http://ctl01:9696
          - interface: internal
            url: http://ctl01:9696
          - interface: admin
            url: http://ctl01:9696
