mysql:
  hosts:
    localhost:

memcached:
  hosts:
    localhost:

rabbitmq:
  hosts:
    localhost:

keystone:
  hosts:
    localhost:

glance:
  hosts:
    localhost:
# placement:
#   hosts:
#     localhost:
#
# nova:
#   hosts:
#     localhost:
#
# neutron:
#   hosts:
#     localhost:
