imports:
  - infra/common/remote_spec.yaml

common:
  namespace: clos
  host: 192.168.210.11
  host_user: admin
  host_pass: admin
  insecure_docker_registry: docker-registry.local.example.com:5000

templates:
  - name: nwnode1
    kind: container
    image: docker-registry.local.example.com:5000/labo/centos7-nwnode:latest

nodes:
  - name: sp1
    templates:
      - nwnode1
