imports:
  - infra/common/remote_spec.yaml

common:
  namespace: clos
  host: 192.168.210.11
  host_user: admin
  host_pass: admin
  nfs_path: /mnt/nfs
  insecure_docker_registry: docker-registry.local.example.com:5000

ipam:
  outer_network1:
    subnet: 10.10.0.0/24
    kind: l2
  spine_network1:
    subnet: 10.10.1.0/24
    kind: l3
  leaf_network1:
    subnet: 10.10.1.0/24
    kind: l3

template_map:
  node:
    kind: container
    image: docker-registry.local.example.com:5000/labo/rocky8-nwnode:latest
    mtu: 9000
    sysctl_map:
      net.ipv6.conf.default.disable_ipv6: 0
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.accept_ra: 0
      net.ipv6.conf.all.accept_ra: 0
  spine:
    lo_ips:
      - inet: "${assign_inet4(spine_network1)}"
    frr:
      id: "${lo_ips.0.ip}"
      asn: "${ipv4_to_asn(lo_ips.0.ip)}"
      bgp_peer_groups:
        - name: ADMIN
  leaf:
    lo_ips:
      - inet: "${assign_inet4(leaf_network1)}"
    frr:
      id: "${lo_ips.0.ip}"
      asn: "${ipv4_to_asn(lo_ips.0.ip)}"
      bgp_peer_groups:
        - name: ADMIN

nodes:
  - name: CL1
    templates:
      - node
    routes:
      - dst: default
        via: ${links.0.peer_ips.0.ip}
    links:
      - peer: SP1
        ips:
          - inet: ${assign_inet4(outer_network1)}
          - inet: ${inet4_to_inet6(links.0.ips.0.inet)}
        peer_ips:
          - inet: ${gateway_inet4(outer_network1)}
  - name: SP1
    templates:
      - node
      - spine
    frr:
      ipv4_networks:
        - "${_node_map.CL1.links.0.ips.0.network}"
      ipv6_networks:
        - "${_node_map.CL1.links.0.ips.1.network}"
    links:
      - peer: L11
        bgp_peer_group: ADMIN
  - name: L11
    templates:
      - node
      - leaf
