- name: Install venv
  shell: |
    set -e

    python3 -m venv {{ placement_venv }} --system-site-packages
    {{ placement_venv }}/bin/pip install pip --upgrade
    mkdir -p /var/log/placement
    mkdir -p /etc/placement

- include_role:
    name: openstack/bobcat/common
    tasks_from: upper_constraints.yaml
  vars:
    dir: "{{ placement_venv }}"

- name: Put pip requirements.txt
  copy:
    src: files/requirements.txt
    dest: "{{ placement_venv }}/requirements.txt"

- name: Install placement
  shell: |
    set -e

    mkdir -p {{ placement_venv }}/src
    cd {{ placement_venv }}/src
    test -e placement || git clone {{ placement_git_repo }} -b {{ placement_git_branch }}

    cd placement
    {{ placement_venv }}/bin/pip install . \
      -r requirements.txt \
      -r {{ placement_venv }}/requirements.txt \
      -c {{ placement_venv }}/upper-constraints.txt
