- name: Put /etc/placement/placement.conf
  template:
    src: placement.conf.j2
    dest: "/etc/placement/placement.conf"
  register: placement_api_conf

- name: Sync DB
  shell: |
    set -e

    mysql -e 'CREATE DATABASE IF NOT EXISTS placement'
    {{ placement_venv }}/bin/placement-manage db sync

- name: Start placement
  shell: |
    set -e

    systemctl reset-failed placement-api || echo 'ignored'
    systemctl status placement-api || systemd-run \
      --unit placement-api -- \
      {{ placement_venv }}/bin/placement-api --port 8778

- name: Restart placement
  when: placement_api_conf.changed
  shell: |
    set -e

    systemctl restart placement-api

- name: Register placement service
  shell: |
    set -e

    source /etc/adminrc
    service_list=$(openstack service list)
    if [[ ! $service_list =~ " placement " ]]; then
      openstack service create --name placement --description "OpenStack Placement" placement
      openstack endpoint create --region "{{ placement_keystone_region }}" placement public "http://{{ placement_keystone_host }}:8778"
      openstack endpoint create --region "{{ placement_keystone_region }}" placement internal "http://{{ placement_keystone_host }}:8778"
      openstack endpoint create --region "{{ placement_keystone_region }}" placement admin "http://{{ placement_keystone_host }}:8778"
    fi

    timeout 5 bash -c 'until openstack resource class list; do sleep 1; done'
