- name: Gather subset
  ansible.builtin.setup:
    gather_subset:
      - distribution

- name: Setup pdns_mysql
  ansible.builtin.include_tasks: setup_pdns_mysql.yml

- name: Setup pdns_mysql
  when: ansible_facts.distribution == "Ubuntu"
  ansible.builtin.include_tasks: setup_stub_resolved.yml

- name: Setup pdns_mysql
  when: ansible_facts.distribution != "Ubuntu"
  ansible.builtin.include_tasks: setup_stub_pdns.yml
