- name: Setup docker
  hosts: docker
  gather_facts: false
  vars:
    docker_iptables: false
  roles:
    - role: labo.infra.docker
      tags: docker

- name: Setup nova_compute
  hosts: nova_compute
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat.nova_compute
      tags: nova_compute

- name: Setup neutron_openvswitch_agent
  hosts: neutron_openvswitch_agent
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat.neutron_openvswitch_agent
      tags: neutron_openvswitch_agent
