- name: Setup workstation
  hosts: workstation
  become: true
  gather_facts: false
  roles:
    - role: workstation
      tags: workstation

- name: Setup common
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat_host.common
      tags: common

- name: Setup memcached
  hosts: memcached
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.memcached
      tags: memcached

- name: Setup mysql
  hosts: mysql
  vars:
    mysql_container_engine: podman
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.mysql
      tags: mysql

- name: Import rabbitmq
  hosts: rabbitmq
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.rabbitmq
      tags: rabbitmq

- name: Setup keystone
  hosts: keystone
  become: true
  gather_facts: false
  vars:
    keystone_runtime: "native"
  roles:
    - role: labo.openstack_bobcat_host.keystone
      tags: keystone

- name: Setup keystone_data
  hosts: localhost
  vars:
    ansible_connection: local
  become: true
  gather_facts: true
  roles:
    - role: labo.openstack_bobcat_host.keystone_data
      tags: keystone_data

- name: Setup glance
  hosts: glance
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat_host.glance
      tags: glance

- name: Setup placement
  hosts: placement
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat_host.placement
      tags: placement

- name: Setup nova
  hosts: nova
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat_host.nova
      tags: nova

- name: Setup neutron
  hosts: neutron
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat_host.neutron
      tags: neutron

- name: Setup openstack_data
  hosts: localhost
  vars:
    ansible_connection: local
  become: true
  gather_facts: true
  roles:
    - role: labo.openstack_bobcat_host.openstack_data
      tags: openstack_data

- name: Setup nova_compute
  hosts: nova_compute
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat_host.nova_compute
      tags: nova_compute

- name: Setup neutron_openvswitch_agent
  hosts: neutron_openvswitch_agent
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat_host.neutron_openvswitch_agent
      tags: neutron_openvswitch_agent

- name: Exec nova_discover_hosts
  hosts: nova
  become: true
  gather_facts: false
  run_once: true
  roles:
    - role: labo.openstack_bobcat_host.cmd_nova_discover_hosts
      tags: cmd_nova_discover_hosts
