#!/bin/bash -x

echo "start myinit"

function retry() {
    local retries=$1
    shift

    local count=0
    until "$@"; do
        exit=$?
        wait=$((2 ** $count))
        count=$(($count + 1))
        if [ $count -lt $retries ]; then
            echo "Retry $count/$retries exited $exit, retrying in $wait seconds..."
            sleep $wait
        else
            echo "Retry $count/$retries exited $exit, no more retries left."
            return $exit
        fi
    done
    return 0
}

# adduser実行時に以下のエラーで追加できない場合があるのでリトライする
# adduser: cannot lock /etc/passwd; try again later.
if ! grep '^admin:' /etc/passwd; then
  retry 5 adduser admin
  echo 'admin:admin' |chpasswd
  groupadd admin
  usermod -a -G admin admin
  echo "%admin  ALL=(ALL:ALL) ALL" >> /etc/sudoers
fi

mkdir -p /mnt/cidata
# mount実行時に以下のエラーで追加できない場合がるのでリトライする
# mount: special device /dev/disk/by-label/cidata does not exist
retry 10 mount /dev/disk/by-label/cidata /mnt/cidata


# Read meta-data
host=`grep hostname: /mnt/cidata/meta-data | awk '{print $2}'`


# ------------------------------
# Setup hostname
hostname $host
echo $host > /etc/hostname
grep "127.0.1.1 $host" /etc/hosts || echo "127.0.1.1 $host" >> /etc/hosts
# ------------------------------


# ------------------------------
# Setup sshd
# Enable password login by ssh
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl enable ssh
systemctl enable sshd
# ------------------------------


# Setup basic
# TODO


# ------------------------------
# Run user-data
# ------------------------------
if [ -e /mnt/cidata/user-data ]; then
    /bin/bash -x /mnt/cidata/user-data
fi


umount /mnt/cidata
rm -rf /mnt/cidata
