#!/bin/bash -x

echo "start myinit"

function retry() {
    local retries=$1
    shift

    local count=0
    until "$@"; do
        exit=$?
        wait=$((2 ** $count))
        count=$(($count + 1))
        if [ $count -lt $retries ]; then
            echo "Retry $count/$retries exited $exit, retrying in $wait seconds..."
            sleep $wait
        else
            echo "Retry $count/$retries exited $exit, no more retries left."
            return $exit
        fi
    done
    return 0
}


# OSの種別の特定
export isCentos=false
export isCentos7=false
export isRocky8=false
grep 'CentOS' /etc/os-release
if [ \$? == 0 ]; then
  export isCentos=true
  grep 'VERSION_ID="7"' /etc/os-release
  if [ \$? == 0 ]; then
    export isCentos7=true
  fi
fi

grep 'Rocky' /etc/os-release
if [ \$? == 0 ]; then
  export isRocky=true
  grep 'VERSION_ID="8.' /etc/os-release
  if [ \$? == 0 ]; then
    export isRocky8=true
  fi
fi

export isUbuntu=false
export isUbuntu18=false
export isUbuntu20=false
grep 'Ubuntu' /etc/os-release
if [ \$? == 0 ]; then
  export isUbuntu=true
  grep 'VERSION_ID="18' /etc/os-release
  if [ \$? == 0 ]; then
    export isUbuntu18=true
  fi
  grep 'VERSION_ID="20' /etc/os-release
  if [ \$? == 0 ]; then
    export isUbuntu20=true
  fi
fi


# cidataをマウントして各種設定を行う
mkdir -p /mnt/cidata
# mount実行時に以下のエラーで追加できない場合がるのでリトライする
# mount: special device /dev/disk/by-label/cidata does not exist
retry 10 mount /dev/disk/by-label/cidata /mnt/cidata


# Read meta-data
host=`grep hostname: /mnt/cidata/meta-data | awk '{print $2}'`


# ------------------------------
# Setup hostname
hostname $host
echo $host > /etc/hostname
grep "127.0.1.1 $host" /etc/hosts || echo "127.0.1.1 $host" >> /etc/hosts
# ------------------------------


# ------------------------------
# Setup sshd
# Enable password login by ssh
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sudo ssh-keygen -A
systemctl enable ssh
systemctl enable sshd
systemctl restart ssh
systemctl restart sshd
# ------------------------------


# Setup basic
# TODO


# ------------------------------
# Run user-data
# ------------------------------
if [ -e /mnt/cidata/user-data ]; then
    /bin/bash -Ex /mnt/cidata/user-data
fi


umount /mnt/cidata
rm -rf /mnt/cidata
