- name: Make directories
  loop:
    - /etc/nova
    - /var/lib/nova/instances
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"

- name: Put api-paste.ini
  ansible.builtin.template:
    src: "api-paste.ini.j2"
    dest: "/etc/nova/api-paste.ini"
    mode: "0600"
  notify:
    - Restart docker nova-services

- name: Put nova.conf
  ansible.builtin.template:
    src: nova.conf.j2
    dest: "/etc/nova/nova.conf"
    mode: "0600"
  notify:
    - Restart docker nova-services

- name: Sync DB
  loop:
    - /opt/nova/bin/nova-manage api_db sync
    - /opt/nova/bin/nova-manage cell_v2 map_cell0
    - bash -xe -c "result=$(/opt/nova/bin/nova-manage cell_v2 list_cells) &&
      (echo $result | grep ' cell1 ' || /opt/nova/bin/nova-manage cell_v2 create_cell --name=cell1 --verbose)"
    - /opt/nova/bin/nova-manage db sync
  community.docker.docker_container:
    name: nova-manage
    image: "{{ nova_image }}"
    command: "{{ item }}"
    network_mode: "host"
    detach: false
    volumes:
      - "/etc/nova:/etc/nova:rw"
    state: started
  changed_when: false

- name: Start nova-services
  loop: "{{ nova_services }}"
  community.docker.docker_container:
    name: "{{ item.name }}"
    network_mode: "host"
    image: "{{ nova_image }}"
    command: "/opt/nova/bin/{{ item.name }}"
    volumes:
      - "/etc/nova:/etc/nova:ro"
      - "/var/lib//nova:/var/lib/nova:rw"
    state: started
