- name: include vars
  hosts: localhost
  tasks:
    - include_tasks: ../common/tasks/include_vars.yaml

- hosts: localhost
  tasks:
    - name: create user
      ansible.builtin.shell: |
        docker ps | grep " mysql$" ||
        (
          (docker ps --all | grep " mysql$" && sudo docker rm mysql || echo "mysql not found") &&
          docker run -v /var/lib/docker-mysql:/var/lib/mysql --net=host --name mysql -e MYSQL_ROOT_PASSWORD={{ mysql_docker_root_password }} -d mysql
        )

    - name: write hostname using jnja2
      ansible.builtin.template:
        src: templates/mysql-docker.j2
        dest: /usr/bin/mysql-docker
        mode: 0755

    - name: waiting for activating
      ansible.builtin.shell: |
        NEXT_WAIT_TIME=0
        until mysql-docker -e "show databases;" || [ $NEXT_WAIT_TIME -eq 4 ]; do
            sleep $((NEXT_WAIT_TIME++))
        done

    - name: create user
      ansible.builtin.shell: |
        mysql-docker -e "CREATE USER IF NOT EXISTS '{{ mysql_docker_user }}'@'%' IDENTIFIED BY '{{ mysql_docker_password }}'"
        mysql-docker -e "GRANT ALL ON *.* TO '{{ mysql_docker_user }}'@'%'; FLUSH PRIVILEGES;"

    - name: write hostname using jnja2
      ansible.builtin.template:
        src: templates/my.cnf.j2
        dest: ~/my.cnf
        mode: 0600
