- name: install
  include_tasks: install.yaml

- name: put /etc/exports
  when: ansible_facts['os_family'] == "Debian"
  become: true
  template:
    src: templates/exports.j2
    dest: /etc/exports
    mode: 0644

- name: export
  when: ansible_facts['os_family'] == "Debian"
  become: true
  shell: |
    set -e
    # exportfs
    # NFSでエクスポートしているファイルシステムのテーブルを管理するために使うコマンド
    # -a すべてのディレクトリをexport/unexportする
    # -r すべてのディレクトリを再exportする、/var/lib/nfs/xtabを/etc/exportsと同期させる
    exportfs -ra
    mkdir -p /mnt/nfs
    mount -t nfs localhost:/ /mnt/nfs
