- name: Put neutron_agent.conf
  template:
    src: neutron_agent.conf.j2
    dest: /etc/neutron/neutron_agent.conf

- name: Put openvswitch_agent.ini
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini

- name: Put metadata_agent.ini
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/metadata_agent.ini

- name: Put dhcp_agent_ini
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/dhcp_agent.ini

- name: Start openvswitch
  service:
    name: openvswitch
    state: restarted

- name: Start neutron-openvswitch-agent
  service:
    name: neutron-openvswitch-agent
    state: started
