imports:
  - infra/local/remote.yaml
  - infra/ovs/vxlan/vxlan3.yaml
  - infra/ovs/vxlan/vxlan3.1.yaml

ipam:
  vtep_network1:
    subnet: 10.10.100.0/24
    kind: l2
  t1vm_network1:
    subnet: 10.100.0.0/24
    kind: l2
  t2vm_network1:
    subnet: 10.100.0.0/24
    kind: l2

template_map:
  hv:
    ovs:
      ex_ip:
        inet: <%=assign_inet4(vtep_network1)%>
      bridges:
        - name: br-ex
          kind: external-ha
        - name: br-t1
          kind: vxlan-tenant-vm
          tenant: 5000
        - name: br-t2
          kind: vxlan-tenant-vm
          tenant: 6000
    frr:
      route_map:
        VM-v4:
          policy: permit
          order: 5
          version: 4
          prefix_list:
            - seq 5 permit <%=ipam.vtep_network1.subnet%> le 32
      ipv4_networks:
        - <%=l3admin.ips.0.inet%>
        # - <%=ovs.ex_ip.inet%>
  vm:
    mtu: 1500
    routes:
      - dst: default
        via: <%=gateway_ip(_links.0.peer_ips.0.network)%>

node_map:
  # HV1:
  # vm_links:
  #   - peer: vm1
  #     peer_ips:
  #       - inet: <%=assign_inet4(vm_network1)%>
  # vms:
  #   - name: vm1
  #     templates:
  #       - node
  #       - vm
  HV1:
    vm_links:
      - peer: t1vm1
        peer_ips:
          - inet: <%=assign_inet4(t1vm_network1)%>
      - peer: t2vm1
        peer_ips:
          - inet: <%=assign_inet4(t2vm_network1)%>
    vms:
      - name: t1vm1
        tenant: 5000
        templates:
          - node
          - vm
        tests:
          - kind: ping
            targets:
              - name: t1vm2
                dst: <%=_node_map.t1vm2._links.0.peer_ips.0.ip%>
      - name: t2vm1
        tenant: 6000
        templates:
          - node
          - vm
        tests:
          - kind: ping
            targets:
              - name: t2vm2
                dst: <%=_node_map.t2vm2._links.0.peer_ips.0.ip%>
  HV2:
    vm_links:
      - peer: t1vm2
        peer_ips:
          - inet: <%=assign_inet4(t1vm_network1)%>
      - peer: t2vm2
        peer_ips:
          - inet: <%=assign_inet4(t2vm_network1)%>
    vms:
      - name: t1vm2
        tenant: 5000
        templates:
          - node
          - vm
      - name: t2vm2
        tenant: 6000
        templates:
          - node
          - vm
