# clos構成でvxlan
imports:
  - infra/local/remote.yaml
  - infra/ovs/vxlan/vxlan3.yaml
  - infra/ovs/vxlan/vxlan3.1.yaml

ipam:
  ovsadmin_network1:
    subnet: 10.10.20.0/24
    kind: l3
  t1vm_network1:
    subnet: 10.100.0.0/24
    kind: l2
  t2vm_network1:
    subnet: 10.100.0.0/24
    kind: l2

template_map:
  hv:
    ovs:
      admin_ips:
        - inet: <%=assign_inet4(ovsadmin_network1)%>
      bridges:
        - name: br-ex
          kind: external-ha
          # links:
          #   - kind: local
          #     flows:
          #       - kind: ingress
          #       - kind: egress
        - name: br-t1
          kind: vxlan-tenant-vm
          tenant: 5000
        - name: br-t2
          kind: vxlan-tenant-vm
          tenant: 6000
    frr:
      route_map:
        VM-v4:
          policy: permit
          order: 5
          version: 4
          prefix_list:
            - seq 6 permit <%=ipam.ovsadmin_network1.subnet%> le 32
      ipv4_networks:
        - <%=l3admin.ips.0.inet%>
        - <%=ovs.admin_ips.0.inet%>
  vm:
    mtu: 1500
    routes:
      - dst: default
        via: <%=gateway_ip(_links.0.peer_ips.0.network)%>

node_map:
  CL1:
    tests:
      - kind: ping
        targets:
          - name: HV1.ovs
            dst: <%=_node_map.HV1.ovs.admin_ips.0.ip%>
          - name: HV2.ovs
            dst: <%=_node_map.HV1.ovs.admin_ips.0.ip%>
  HV1:
    vm_links:
      - peer: t1vm1
        peer_ips:
          - inet: <%=assign_inet4(t1vm_network1)%>
      - peer: t2vm1
        peer_ips:
          - inet: <%=assign_inet4(t2vm_network1)%>
    vms:
      - name: t1vm1
        tenant: 5000
        templates:
          - node
          - vm
        tests:
          - kind: ping
            targets:
              - name: t1vm2
                dst: <%=_node_map.t1vm2._links.0.peer_ips.0.ip%>
      - name: t2vm1
        tenant: 6000
        templates:
          - node
          - vm
        tests:
          - kind: ping
            targets:
              - name: t2vm2
                dst: <%=_node_map.t2vm2._links.0.peer_ips.0.ip%>
  HV2:
    vm_links:
      - peer: t1vm2
        peer_ips:
          - inet: <%=assign_inet4(t1vm_network1)%>
      - peer: t2vm2
        peer_ips:
          - inet: <%=assign_inet4(t2vm_network1)%>
    vms:
      - name: t1vm2
        tenant: 5000
        templates:
          - node
          - vm
      - name: t2vm2
        tenant: 6000
        templates:
          - node
          - vm
