- name: Install kind
  ansible.builtin.shell: |
    if ! command kind; then
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
      sudo install -o root -g root -m 0755 kind /usr/bin/kind
      rm ./kind
    fi
  changed_when: false

- name: Put kind.yml
  ansible.builtin.template:
    src: kind.yml.j2
    dest: /etc/ansible/kind.yml
    mode: "0644"

- name: Create cluster
  ansible.builtin.shell: kind get clusters | grep kind || kind create cluster --config /etc/ansible/kind.yml
  changed_when: false

- name: Put kubeconfig
  ansible.builtin.shell: |
    kind export -n kind kubeconfig
