- include_role:
    name: openstack/bobcat/nova
    tasks_from: config.yaml

- name: Put libvirtd.conf
  template:
    src: libvirtd.conf.j2
    dest: "/etc/libvirt/libvirtd.conf"
  register: libvirtd_conf

- name: Put nova-compute.conf
  template:
    src: nova-compute.conf.j2
    dest: "/etc/nova/nova-compute.conf"
  register: nova_compute_conf

- name: Start libvirtd
  service:
    name: libvirtd
    state: started

- name: Start nova-compute
  service:
    name: nova-compute
    state: started

- name: Restart nova-compute
  when: nova_conf.changed or nova_compute_conf.changed
  service:
    name: nova-compute
    state: restarted
