- include_role:
    name: openstack/bobcat/nova
    tasks_from: config.yaml

- name: Put nova-compute.conf
  template:
    src: nova-compute.conf.j2
    dest: "/etc/nova/nova-compute.conf"
  register: nova_compute_conf

- name: Start libvirtd
  service:
    name: libvirtd
    state: started

- name: Start nova-compute
  shell: |
    set -e

    systemctl reset-failed nova-compute || echo 'ignored'
    systemctl status nova-compute || systemd-run \
      --unit nova-compute -- \
      {{ nova_venv }}/bin/nova-compute --config-file /etc/nova/nova.conf --log-file /var/log/nova/nova-compute.log

- name: Restart nova-compute
  when: nova_conf.changed or nova_compute_conf.changed
  service:
    name: nova-compute
    state: restarted
