common:
  namespace: local

infras:
  - kind: mysql
    name: mysql
  - kind: pdns
    name: resolver
    ns: 192.168.210.1
    records:
      - type: a
        name: docker-registry
        content: 192.168.210.1
  - kind: nfs
    name: nfs
    path: /var/nfs/exports
    local_path: /mnt/nfs
    exports:
      - 192.168.210.0/24

vm_images:
  - name: centos7
    url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz
    nfs: nfs1
    path: centos7
  - name: centos7_custom
    base: centos7

templates:
  - name: vm1
    kind: vm
    vcpus: 4
    ram: 4096
    disk: 40
    image: centos7_custom
    routes:
      default: 192.168.210.1
    resolvers:
      - 192.168.210.1

nodes:
  - kind: gw
    name: gw1
    ip: 192.168.210.1/24
    links:
      - peer: vm1
        peer_ips:
          - inet: 192.168.210.11/24
      - peer: vm2
        peer_ips:
          - inet: 192.168.210.12/24
  - name: vm1
    templates: [vm1]
  - name: vm2
    templates: [vm1]
