nova_execution_mode: docker
nova_image: "{{ global_docker_registry }}/local/bobcat-nova:latest"

nova_venv: /opt/nova
nova_git_repo: https://github.com/openstack/nova.git
nova_git_branch: stable/2023.2
nova_upper_constraints: https://raw.githubusercontent.com/openstack/requirements/stable/2023.2/upper-constraints.txt

nova_my_ip: 127.0.0.1

nova_services:
  - name: nova-api
  - name: nova-scheduler
  - name: nova-conductor
