imports:
  - /etc/ansible/host_vars/localhost.yaml

template_map:
  node:
    kind: container
    spec:
      image: local/rocky9-nwnode:latest
      mtu: 9000
      sysctl_map:
        net.ipv4.tcp_l3mdev_accept: 1
        net.ipv4.udp_l3mdev_accept: 1
        net.vrf.strict_mode: 1
        net.ipv6.conf.default.disable_ipv6: 0
        net.ipv6.conf.all.disable_ipv6: 0
        net.ipv6.conf.default.accept_ra: 0
        net.ipv6.conf.all.accept_ra: 0
        net.ipv4.conf.all.rp_filter: 0
        net.ipv4.conf.all.forwarding: 1
        net.ipv4.conf.default.forwarding: 1
        net.ipv6.conf.all.forwarding: 1
        net.ipv6.conf.default.forwarding: 1
        net.ipv6.conf.all.seg6_enabled: 1
        net.ipv6.conf.default.seg6_enabled: 1
  frr:
    spec:
      steps:
        - template:
            src: frr/daemons.j2
            dst: /etc/frr/daemons
        - template:
            src: frr/frr.conf.j2
            dst: /etc/frr/frr.conf
        - shell:
            cmds:
              - sed -i 's/StartLimitInterval=.*/StartLimitInterval=10s/' /usr/lib/systemd/system/frr.service
              - systemctl restart frr
  aggregator:
    spec:
      lo_ips:
        - inet: <%=assign_inet4("spine_network")%>
      vars:
        frr_bgp_asn: <%=ipv4_to_asn(_node.spec.lo_ips.0.ip)%>
        frr_bgp_router_id: <%=_node.spec.lo_ips.0.ip%>
        frr_bgp_peer_groups:
          - name: ADMIN
        frr_bgp_ipv4_unicast_networks:
          - <%=_node_map.CL1.spec.links.0.ips.0.network%>
          - <%=lo_ips.0.inet%>
        frr_bgp_ipv6_unicast_networks:
          - <%=_node_map.CL1.spec.links.0.ips.1.network%>
  spine:
    spec:
      lo_ips:
        - inet: <%=assign_inet4("spine_network")%>
      vars:
        frr_bgp_asn: <%=ipv4_to_asn(_node.spec.lo_ips.0.ip)%>
        frr_bgp_router_id: <%=_node.spec.lo_ips.0.ip%>
        frr_bgp_peer_groups:
          - name: ADMIN
        frr_bgp_ipv4_unicast_networks:
          - <%=_node.spec.lo_ips.0.inet%>
  leaf:
    spec:
      lo_ips:
        - inet: <%=assign_inet4("leaf_network")%>
      vars:
        frr_bgp_asn: <%=ipv4_to_asn(_node.spec.lo_ips.0.ip)%>
        frr_bgp_router_id: <%=_node.spec.lo_ips.0.ip%>
        frr_bgp_peer_groups:
          - name: ADMIN
        frr_bgp_ipv4_unicast_networks:
          - <%=_node.spec.lo_ips.0.inet%>
  hv:
    spec:
      lo_ips:
        - inet: <%=assign_inet4("hv_network")%>
        - inet: <%=asn_to_sid(_node.spec.vars.frr_bgp_asn)%>
      vars:
        frr_bgp_asn: <%=ipv4_to_asn(_node.spec.lo_ips.0.ip)%>
        frr_bgp_router_id: <%=_node.spec.lo_ips.0.ip%>
        frr_bgp_peer_groups:
          - name: ADMIN
        frr_bgp_ipv4_unicast_networks:
          - <%=_node.spec.lo_ips.0.inet%>
        frr_bgp_ipv6_unicast_networks:
          - <%=_node.spec.lo_ips.1.inet%>
  vm:
    spec:
      mtu: 1500
      routes:
        - dst: default
          via: <%=gateway_ip(_node.spec._links.0.peer_ips.0.network)%>

kind: Infra
name: ovsvxlan
spec:
  ipam:
    outer_network1:
      subnet: 10.10.0.0/24
      kind: l2
    spine_network:
      subnet: 10.10.1.0/24
      kind: l3
    leaf_network:
      subnet: 10.10.2.0/24
      kind: l3
    hv_network:
      subnet: 10.10.20.0/24
      kind: l3
    t1vm_network1:
      subnet: 10.100.0.0/24
      kind: l2
    t1vm_network2:
      subnet: 10.100.1.0/24
      kind: l2
    t2vm_network1:
      subnet: 10.100.0.0/24
      kind: l2
    t2vm_network2:
      subnet: 10.100.1.0/24
      kind: l2

  nodes:
    - name: CL1
      templates:
        - node
      spec:
        routes:
          - dst: default
            via: <%=_node.spec.links.0.peer_ips.0.ip%>
        links:
          - peer: AG1
            ips:
              - inet: <%=assign_inet4("outer_network1")%>
              - inet: <%=inet4_to_inet6(_node.spec.links.0.ips.0.inet)%>
            peer_ips:
              - inet: <%=gateway_inet4("outer_network1")%>
        tests:
          - shell:
              cmds:
                - ping -c 1 -W 1 <%=_node_map.SP1.spec.lo_ips.0.ip%>
                - ping -c 1 -W 1 <%=_node_map.SP2.spec.lo_ips.0.ip%>
                - ping -c 1 -W 1 <%=_node_map.L11.spec.lo_ips.0.ip%>
                - ping -c 1 -W 1 <%=_node_map.L12.spec.lo_ips.0.ip%>
                - ping -c 1 -W 1 <%=_node_map.L21.spec.lo_ips.0.ip%>
                - ping -c 1 -W 1 <%=_node_map.L22.spec.lo_ips.0.ip%>
                - ping -c 1 -W 1 <%=_node_map.HV1.spec.lo_ips.0.ip%>
                - ping -c 1 -W 1 <%=_node_map.HV2.spec.lo_ips.0.ip%>
    - name: AG1
      templates:
        - node
        - aggregator
        - frr
      spec:
        links:
          - peer: SP1
            bgp_peer_group: ADMIN
          - peer: SP2
            bgp_peer_group: ADMIN
    - name: SP1
      templates:
        - node
        - spine
        - frr
      spec:
        links:
          - peer: L11
            bgp_peer_group: ADMIN
          - peer: L12
            bgp_peer_group: ADMIN
          - peer: L21
            bgp_peer_group: ADMIN
          - peer: L22
            bgp_peer_group: ADMIN
    - name: SP2
      templates:
        - node
        - spine
        - frr
      spec:
        links:
          - peer: L11
            bgp_peer_group: ADMIN
          - peer: L12
            bgp_peer_group: ADMIN
          - peer: L21
            bgp_peer_group: ADMIN
          - peer: L22
            bgp_peer_group: ADMIN
    - name: L11
      templates:
        - node
        - leaf
        - frr
      spec:
        links:
          - peer: HV1
            bgp_peer_group: ADMIN
    - name: L12
      templates:
        - node
        - leaf
        - frr
    - name: L21
      templates:
        - node
        - leaf
        - frr
      spec:
        links:
          - peer: HV2
            bgp_peer_group: ADMIN
    - name: L22
      templates:
        - node
        - leaf
        - frr
    - name: HV1
      templates:
        - node
        - hv
      spec:
        links:
          - peer: t1vm1
            peer_ips:
              - inet: <%=assign_inet4("t1vm_network2")%>
          - peer: t2vm1
            peer_ips:
              - inet: <%=assign_inet4("t2vm_network2")%>
        steps:
          - template:
              src: frr/daemons.j2
              dst: /etc/frr/daemons
          - template:
              src: frr/frr.conf.j2
              dst: /etc/frr/frr.conf
          - shell:
              cmds:
                - sed -i 's/StartLimitInterval=.*/StartLimitInterval=10s/' /usr/lib/systemd/system/frr.service
                - systemctl restart frr
          - shell:
              cmds:
                - mkdir -p /etc/iproute2
                - touch /etc/iproute2/rt_tables
                - grep "100 localsid" /etc/iproute2/rt_tables || echo "100 localsid" >> /etc/iproute2/rt_tables
                - ip -6 rule add to <%=_node.spec.lo_ips.1.network%> lookup localsid
                - ip -6 route add blackhole default table localsid | echo "ignored"

                # vpc50の設定
                - ip link add dev vrf50 type vrf table 50 | echo "ignored"
                - ip link set dev vrf50 up
                - ip vrf show
                - ip link set dev HV1_0_t1vm1 master vrf50
                - ip -6 route add `echo <%=_node.spec.lo_ips.1.network%>|sed -e "s|::/64|::0050|g"` encap seg6local action End.DX4 nh4 169.254.1.50 dev vrf50 table localsid | echo "ignored"
                - ip route add 169.254.1.50 dev vrf50 | echo "ignored"
                - ip route add 10.100.1.3 encap seg6 mode encap segs `echo <%=_node_map.HV2.spec.lo_ips.1.network%>|sed -e "s|::/64|::0050|g"` dev HV1_0_L11 table 50 | echo "ignored"
                - ip route add 10.100.1.2 dev HV1_0_t1vm1 table 50 | echo "ignored"
                - ip addr add 10.100.1.1/24 dev HV1_0_t1vm1 | echo "ignored"
                - sysctl -w net.ipv4.conf.HV1_0_t1vm1.proxy_arp=1
    - name: HV2
      templates:
        - node
        - hv
      spec:
        links:
          - peer: t1vm2
            peer_ips:
              - inet: <%=assign_inet4("t1vm_network2")%>
          - peer: t2vm2
            peer_ips:
              - inet: <%=assign_inet4("t2vm_network2")%>
        steps:
          - template:
              src: frr/daemons.j2
              dst: /etc/frr/daemons
          - template:
              src: frr/frr.conf.j2
              dst: /etc/frr/frr.conf
          - shell:
              cmds:
                - sed -i 's/StartLimitInterval=.*/StartLimitInterval=10s/' /usr/lib/systemd/system/frr.service
                - systemctl restart frr
          - shell:
              cmds:
                - mkdir -p /etc/iproute2
                - touch /etc/iproute2/rt_tables
                - grep "100 localsid" /etc/iproute2/rt_tables || echo "100 localsid" >> /etc/iproute2/rt_tables
                - ip -6 rule add to <%=_node.spec.lo_ips.1.network%> lookup localsid
                - ip -6 route add blackhole default table localsid | echo "ignored"

                # vpc50の設定
                - ip link add dev vrf50 type vrf table 50 | echo "ignored"
                - ip link set dev vrf50 up
                - ip vrf show
                - ip link set dev HV2_0_t1vm2 master vrf50
                - ip -6 route add `echo <%=_node.spec.lo_ips.1.network%>|sed -e "s|::/64|::0050|g"` encap seg6local action End.DX4 nh4 169.254.1.50 dev vrf50 table localsid | echo "ignored"
                - ip route add 169.254.1.50 dev vrf50 | echo "ignored"
                - ip route add 10.100.1.2 encap seg6 mode encap segs `echo <%=_node_map.HV1.spec.lo_ips.1.network%>|sed -e "s|::/64|::0050|g"` dev HV2_0_L21 table 50 | echo "ignored"
                - ip route add 10.100.1.3 dev HV2_0_t1vm2 table 50 | echo "ignored"
                - ip addr add 10.100.1.1/24 dev HV2_0_t1vm2 | echo "ignored"
                - sysctl -w net.ipv4.conf.HV2_0_t1vm2.proxy_arp=1
    - name: t1vm1
      templates:
        - node
        - vm
      spec:
        tests:
          - shell:
              cmds:
                - ping -c 1 -W 1 <%=_node_map.t1vm2.spec._links.0.peer_ips.0.ip%>
    - name: t2vm1
      templates:
        - node
        - vm
    - name: t1vm2
      templates:
        - node
        - vm
    - name: t2vm2
      templates:
        - node
        - vm
