#!/bin/bash -xe

WD="${1}"
shift

sudo docker run --rm \
    -v "${HOME}:${HOME}:ro" \
    -v "/root/.ssh:/root/.ssh:ro" \
    -v "./inventories:/etc/ansible/inventories:ro" \
    -v "./scripts:/etc/ansible/scripts:ro" \
    -v "/mnt/nfs/labo/ansible/collections:/etc/ansible/collections:ro" \
    --network openstack-bobcat_default \
    -w "${WD}" \
    local/ansible $*
