- name: start docker-registry on docker
  become: true
  vars:
    name: docker-registry
  shell: |
    docker ps | grep " {{ name }}$" ||
    (
      (sudo docker ps --all | grep " {{ name }}$" && sudo docker rm "{{ name }}" || echo "{{ name }} not found") &&
      sudo docker run -d --rm -p 5050:5000 --name {{ name }} \
            -v "/var/lib/{{ name }}":/var/lib/registry \
            registry:2
    )
