- name: Setup docker
  hosts: docker
  vars:
    docker_iptables: false
  roles:
    - role: labo.infra.docker
      tags: docker

- name: Setup memcached
  hosts: memcached
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.memcached
      tags: memcached

- name: Setup mysql
  hosts: mysql
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.mysql
      tags: mysql

- name: Import rabbitmq
  hosts: rabbitmq
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.rabbitmq
      tags: rabbitmq

- name: Setup keystone
  hosts: keystone
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat.keystone
      tags: keystone

- name: Setup keystone_data
  hosts: workstation
  become: true
  gather_facts: false
  roles:
    - role: workstation
      tags: workstation
    - role: labo.openstack_bobcat.keystone_data
      tags: keystone_data
