- name: Setup docker
  hosts:
    - workstation
  gather_facts: false
  vars:
    docker_iptables: false
  roles:
    - role: labo.infra.docker
      tags: docker

- name: Setup workstation
  hosts: workstation
  become: true
  gather_facts: false
  roles:
    - role: workstation
      tags: workstation

- name: Setup memcached
  hosts: memcached
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.memcached
      tags: memcached

- name: Setup mysql
  hosts: mysql
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.mysql
      tags: mysql

- name: Import rabbitmq
  hosts: rabbitmq
  become: true
  gather_facts: false
  roles:
    - role: labo.infra.rabbitmq
      tags: rabbitmq

- name: Setup keystone on k8s
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    keystone_execution_mode: k8s
  roles:
    - role: labo.openstack_bobcat.keystone
      tags: keystone

- name: Setup keystone_data
  hosts: workstation
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat.keystone_data
      tags: keystone_data

- name: Setup k8s
  hosts: workstation
  become: true
  gather_facts: false
  vars:
    glance_execution_mode: k8s
    neutron_execution_mode: k8s
    placement_execution_mode: k8s
    nova_execution_mode: k8s
  roles:
    - role: labo.openstack_bobcat.glance
      tags: glance
    - role: labo.openstack_bobcat.neutron
      tags: neutron
    - role: labo.openstack_bobcat.nova
      tags: nova
    - role: labo.openstack_bobcat.placement
      tags: placement

- name: Setup openstack_data
  hosts: workstation
  become: true
  gather_facts: false
  roles:
    - role: labo.openstack_bobcat.openstack_data
      tags: openstack_data

- name: Exec nova_discover_hosts
  hosts: nova
  become: true
  gather_facts: false
  run_once: true
  roles:
    - role: labo.openstack_bobcat.cmd_nova_discover_hosts
      tags: cmd_nova_discover_hosts
