# prettier-ignore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone-public
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keystone_public_deployment_replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: keystone
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.keystone_image }}"
          imagePullPolicy: IfNotPresent
          command:
            - /opt/keystone/bin/keystone-wsgi-public
            - --port
            - "80"
          env:
            - name: OS_KEYSTONE_CONFIG_FILES
              value: /etc/keystone/keystone.conf;/etc/keystone/secret/keystone-secret.conf
          ports:
            - name: keystone-public
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: keystone-public
          readinessProbe:
            httpGet:
              path: /
              port: keystone-public
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: etc-keystone
              mountPath: /etc/keystone
            - name: etc-keystone-secret
              mountPath: /etc/keystone/secret
            - name: etc-keystone-credential-keys
              mountPath: /etc/keystone/credential-keys
            - name: etc-keystone-fernet-keys
              mountPath: /etc/keystone/fernet-keys
      volumes:
        - name: etc-keystone
          configMap:
            name: etc-keystone
        - name: etc-keystone-secret
          secret:
            secretName: etc-keystone-secret
        - name: etc-keystone-credential-keys
          secret:
            secretName: etc-keystone-credential-keys
        - name: etc-keystone-fernet-keys
          secret:
            secretName: etc-keystone-fernet-keys
