- name: Start keycloak
  community.docker.docker_container:
    name: keycloak
    image: "{{ keycloak_image }}"
    command: start-dev
      --https-certificate-file=/etc/x509/https/certs/tls.crt
      --https-certificate-key-file=/etc/x509/https/certs/tls.key
    env:
      KEYCLOAK_ADMIN: "{{ keycloak_admin_user }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_admin_password }}"
    volumes:
      - "/etc/labo/tls-assets/server.pem:/etc/x509/https/certs/tls.crt:ro"
      - "/etc/labo/tls-assets/server-key.pem:/etc/x509/https/certs/tls.key:ro"
