- name: Install mysql-server
  when: ansible_facts['os_family'] == "RedHat"
    and (
    ansible_facts["distribution_major_version"] == "8"
    or ansible_facts["distribution_major_version"] == "9"
    )
  yum:
    name: mysql-server
