- name: install
  include_tasks: install.yaml

- name: Start service docker, if not started
  when: ansible_facts['os_family'] == "RedHat"
  ansible.builtin.service:
    name: mysqld
    state: started

- name: Start service docker, if not started
  when: ansible_facts['os_family'] != "RedHat"
  ansible.builtin.service:
    name: mysql
    state: started

- name: create user
  ansible.builtin.shell: |
    mysql -e "CREATE USER IF NOT EXISTS '{{ mysql_user }}'@'%' IDENTIFIED BY '{{ mysql_password }}'"
    mysql -e "GRANT ALL ON *.* TO '{{ mysql_user }}'@'%'; FLUSH PRIVILEGES;"
