- name: Start mysql
  when: ansible_facts['os_family'] == "RedHat"
  service:
    name: mysqld
    state: started

- name: Waiting for activating
  shell: |
    set -e
    NEXT_WAIT_TIME=0
    until mysql -e "show databases;" || [ $NEXT_WAIT_TIME -eq 4 ]; do
        sleep $((NEXT_WAIT_TIME++))
    done

- name: Create user
  shell: |
    set -e
    mysql -e "CREATE USER IF NOT EXISTS '{{ mysql_user }}'@'%' IDENTIFIED BY '{{ mysql_password }}'"
    mysql -e "GRANT ALL ON *.* TO '{{ mysql_user }}'@'%'; FLUSH PRIVILEGES;"
