# prettier-ignore
---
# This ConfigMap is unused, but this is needed to confirm the diff of placement.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: unused-etc-placement
data:
  placement.conf: |
{{ .Values.placement_conf | nindent 4 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: etc-placement-secret
data:
  placement.conf: {{ .Values.secret_placement_conf | b64enc }}
