- name: ovs
  shell: |
    systemctl start openvswitch

- name: ovs_lib
  when: ovs_hv_vxlan is defined
  ovs_hv_vxlan:
    ovs: "{{ ovs_hv_vxlan }}"

- name: ovs_hv_clos
  when: ovs_hv_clos is defined
  ovs_hv_clos:
    ovs: "{{ ovs_hv_clos }}"
