- name: Exec net-destroy default
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    set -e -o pipefail
    virsh net-info default | grep 'Active:.*no' || virsh net-destroy default
  changed_when: false
