# prettier-ignore
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ingressClassName: haproxy
  rules:
    - host: {{ required "required" .Values.region_glance_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance-api
                port:
                  number: 9292
