pdns_mysql_host: 127.0.0.1
pdns_mysql_port: 3306
pdns_mysql_user: admin
pdns_mysql_password: adminpass

pdns_local_address: 0.0.0.0
pdns_domains:
  - example.com
pdns_records:
  - domain: example.com
    name: docker-registry.example.com
    type: a
    content: "{{ local_ipaddr }}"
