- name: Put keystone.conf
  ansible.builtin.template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
  register: keystone_conf

- name: Sync DB
  ansible.builtin.shell: |
    set -e

    /opt/keystone/bin/keystone-manage \
      db_sync

    /opt/keystone/bin/keystone-manage \
      fernet_setup --keystone-user nobody --keystone-group nobody

    /opt/keystone/bin/keystone-manage \
      credential_setup --keystone-user nobody --keystone-group nobody

    /opt/keystone/bin/keystone-manage \
      bootstrap --bootstrap-password "{{ keystone_admin_password }}" \
      --bootstrap-admin-url "http://{{ keystone_host }}:5000/v3/" \
      --bootstrap-internal-url "http://{{ keystone_host }}:5000/v3/" \
      --bootstrap-public-url "http://{{ keystone_host }}:5000/v3/" \
      --bootstrap-region-id "{{ keystone_region }}"

- name: Start keystone
  when: keystone_runtime == "native"
  ansible.builtin.shell: |
    systemctl status keystone-public || systemd-run --unit keystone-public -- \
      /opt/keystone/bin/keystone-wsgi-public --port 5000

- name: Restart keystone
  when: keystone_runtime == "native"
  when: keystone_conf.changed
  ansible.builtin.shell: |
    systemctl restart keystone-public

- name: Put wsgi-keystone.conf
  when: keystone_runtime == "httpd"
  ansible.builtin.template:
    src: wsgi-keystone.conf.j2
    dest: /etc/httpd/conf.d/wsgi-keystone.conf
  register: wsgi_keystone_conf

- name: Start keystone httpd
  when: keystone_runtime == "httpd"
  ansible.builtin.shell: |
    systemctl start httpd

- name: Restart keystone httpd
  when: keystone_runtime == "httpd"
    and (keystone_conf.changed or wsgi_keystone_conf.changed)
  ansible.builtin.shell: |
    systemctl restart httpd

# - name: Put adminrc
#   ansible.builtin.template:
#     src: adminrc.j2
#     dest: /etc/adminrc

# 
# - name: Create user
#   ansible.builtin.shell: |
#     set -e
# 
#     source /etc/adminrc
# 
#     timeout 5 bash -c 'until openstack token issue; do sleep 1; done'
# 
#     openstack project show service || openstack project create --domain default --description "Service Project" service
#     openstack user show "{{ keystone_service_user }}" || openstack user create --domain default --password "{{ keystone_service_password }}" "{{ keystone_service_user }}"
#     openstack role add --project service --user "{{ keystone_service_user }}" admin
