- name: include vars
  hosts: localhost
  tasks:
    - include_tasks: ../common/tasks/include_vars.yaml

- hosts: localhost
  tasks:
    - name: install
      when: not is_container
      include_tasks: tasks/install.yaml

    - ansible.builtin.template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
      register: docker_daemon_json

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started

    - name: Restart docker
      when: docker_daemon_json.changed
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: mkdir for netns
      ansible.builtin.shell: |
        mkdir -p /var/run/netns
