- name: Put /etc/placement/placement.conf
  ansible.builtin.template:
    src: placement.conf.j2
    dest: "/etc/placement/placement.conf"
  notify: Restart placement-api

- name: Sync DB
  ansible.builtin.command: {{ placement_venv }}/bin/placement-manage db sync
  changed_when: false

- name: Start placement
  ansible.builtin.shell: |
    set -e

    systemctl reset-failed placement-api || echo 'ignored'
    systemctl status placement-api || systemd-run \
      --unit placement-api -- \
      {{ placement_venv }}/bin/placement-api --port 8778
  changed_when: false
