- name: Host main
  when: keystone_execution_mode == "host"
  ansible.builtin.include_tasks: host/main.yml

- name: Docker main
  when: keystone_execution_mode == "docker"
  ansible.builtin.include_tasks: docker/main.yml
