- name: Install helm
  ansible.builtin.shell: |
    if ! commnd helm; then
      curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz
      tar xf helm.tar.gz
      sudo install -o root -g root -m 0755 linux-amd64/helm /usr/local/bin/helm
      rm -rf linux-amd64
      rm helm.tar.gz
    fi
