- name: Make directories
  loop:
    - /etc/neutron
    - /etc/neutron/plugins/ml2
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"

- name: Put neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    mode: "0600"
  notify:
    - Restart docker neutron-server

- name: Put ml2_conf.ini
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    mode: "0644"
  notify:
    - Restart docker neutron-server

- name: Put api-paste.ini
  ansible.builtin.template:
    src: "api-paste.ini.j2"
    dest: "/etc/neutron/api-paste.ini"
    mode: "0644"
  notify:
    - Restart docker neutron-server

- name: Sync DB
  loop:
    - /opt/neutron/bin/neutron-db-manage --config-file /etc/neutron/neutron.conf
      --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  community.docker.docker_container:
    name: neutron-db-manage
    image: "{{ neutron_image }}"
    command: "{{ item }}"
    network_mode: "host"
    detach: false
    volumes:
      - "/etc/neutron:/etc/neutron:rw"
    state: started
  changed_when: false

- name: Start neutron-server
  community.docker.docker_container:
    name: "neutron-server"
    network_mode: "host"
    image: "{{ neutron_image }}"
    command: "/opt/neutron/bin/neutron-server"
    volumes:
      - "/etc/neutron:/etc/neutron:ro"
    state: started
