[uwsgi]
plugin = python312
chdir = /opt/placement
virtualenv = /opt/placement
module = placement.wsgi.api:application

strict = true
need-app = true
master = true

http-socket = 0.0.0.0:8778

# === プロセス設定 ===
processes = 1
threads = 1
enable-threads = true

# Override the default size for headers from the 4k default.
buffer-size = 65535

# uwsgi recommends this to prevent thundering herd on accept.
thunder-lock = true
# This ensures that file descriptors aren't shared between keystone processes.
lazy-apps = true

harakiri = 120
max-requests = 1000
