- name: Gather subset
  ansible.builtin.setup:
    gather_subset: default_ipv4

- name: Setup libvirt
  ansible.builtin.include_tasks: setup_libvirt.yml

- include_role:
    name: labo.openstack_bobcat_host.nova
    tasks_from: install.yml

- name: Install
  ansible.builtin.include_tasks: install.yml

- name: Setup
  ansible.builtin.include_tasks: setup.yml
