- name: Host main
  when: placement_execution_mode == "host"
  ansible.builtin.include_tasks: host/main.yml

- name: Docker main
  when: placement_execution_mode == "docker"
  ansible.builtin.include_tasks: docker/main.yml

- name: Main on k8s
  when: placement_execution_mode == "k8s"
  ansible.builtin.include_tasks: k8s/main.yml
