- name: Create region
  environment: "{{ global_keystone_admin_envs }}"
  ansible.builtin.shell: |
    set -e -o pipefail

    stdout=$(openstack region list -f value -c Region)
    if ! echo "${stdout}" | grep "{{ region_endpoint.region }}"; then
      openstack region create "{{ region_endpoint.region }}"
    fi
  changed_when: false

- name: Create endpoints
  with_subelements:
    - "{{ region_endpoint.services }}"
    - endpoints
  openstack.cloud.endpoint:
    auth: "{{ global_keystone_admin_auth }}"
    region: "{{ region_endpoint.region }}"
    service: "{{ item.0.service }}"
    endpoint_interface: "{{ item.1.interface }}"
    url: "{{ item.1.url }}"
