route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'null'
  routes:
  - match:
      job: myjob
    receiver: 'web.hook'
receivers:
- name: 'null'
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
inhibit_rules:
- target_matchers: [ severity="warning" ]
  source_matchers: [ severity="critical" ]
  equal: ['alertname', 'instance']
