- name: put daemons
  template:
    src: templates/daemons.j2
    dest: /etc/frr/daemons

- name: restart frr
  shell: |
    sed -i 's/StartLimitInterval=.*/StartLimitInterval=10s/' /usr/lib/systemd/system/frr.service
    systemctl daemon-reload
    systemctl restart frr

- name: put frr.conf
  template:
    src: templates/frr.conf.j2
    dest: /etc/frr/frr.conf

- name: vtysh
  shell: |
    systemctl reload frr

# - name: debug
#   ansible.builtin.shell: |
#     mysql -e "CREATE USER IF NOT EXISTS '{{ mysql_user }}'@'%' IDENTIFIED BY '{{ mysql_password }}'"
#     mysql -e "GRANT ALL ON *.* TO '{{ mysql_user }}'@'%'; FLUSH PRIVILEGES;"
