- name: Install docker for rh
  when: ansible_facts['os_family'] == "RedHat"
  become: true
  shell: |
    yum install -y yum-utils
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum install -y docker-ce-3:24.0.8-1.el8 \
                   docker-ce-cli-1:24.0.8-1.el8 \
                   containerd.io-1.6.26-3.1.el8

- name: Install docker for ubuntu
  when: ansible_facts['os_family'] == "Debian"
  become: true
  shell: |
    set -xe
    apt update
    apt install -y apt-transport-https ca-certificates curl gnupg lsb-release
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list >/dev/null
    apt update
    apt install -y "docker-ce=5:24.0.8-1~ubuntu.22.04~jammy" \
                   "docker-ce-cli=5:24.0.8-1~ubuntu.22.04~jammy" \
                   "containerd.io=1.6.26-1"
