- name: install
  include_tasks: install.yaml

- name: put /etc/docker/daemon.json
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  register: docker_daemon_json

- name: start docker
  become: true
  service:
    name: docker
    state: started

- name: restart docker when config changed
  become: true
  when: docker_daemon_json.changed
  service:
    name: docker
    state: restarted

- name: mkdir for netns
  become: true
  shell: |
    mkdir -p /var/run/netns

- name: create docker networks
  loop: "{{ docker_networks }}"
  include_tasks: create_network.yaml
