- name: Set helm_release_values
  vars:
    self_values: "{{ hostvars[inventory_hostname] }}"
    extra_values:
      nova_conf: "{{ lookup('template', './nova.conf.j2') }}"
      nova_api_paste_ini: "{{ lookup('template', './api-paste.ini.j2') }}"
      secret_nova_conf: "{{ lookup('template', './secret/nova.conf.j2') }}"
  ansible.builtin.set_fact:
    helm_release_values: "{{ self_values | combine(extra_values) }}"

- name: Deploy nova
  kubernetes.core.helm:
    name: nova
    release_namespace: nova
    chart_ref: /etc/ansible/collections/ansible_collections/labo/openstack_bobcat/charts/nova
    release_values: "{{ helm_release_values }}"
    create_namespace: true
    atomic: true
    timeout: 1m
