# NOTE About how extra_values.placement_conf and extra_values.secret_placement_conf are handled
# Because placement-api cannot have multiple configuration files, placement.conf must be single file.
# extra_values.placement_conf is unused on pod, but this is needed to confirm the diff of placement.conf without secret.
# extra_values.secret_placement_conf is used as single placement.conf on pod.
# The diff of extra_values.secret_placement_conf cannot be confirmed, because this is managed as a secret resource on k8s.
- name: Set helm_release_values
  vars:
    self_values: "{{ hostvars[inventory_hostname] }}"
    extra_values:
      placement_conf: "{{ lookup('template', './placement.conf.j2') }}"
      secret_placement_conf: |
        {{ lookup('template', './placement.conf.j2') }}
        # ----
        {{ lookup('template', './secret/placement.conf.j2') }}
  ansible.builtin.set_fact:
    helm_release_values: "{{ self_values | combine(extra_values) }}"

- name: Deploy placement
  kubernetes.core.helm:
    name: placement
    release_namespace: placement
    chart_ref: /etc/ansible/collections/ansible_collections/labo/openstack_bobcat/charts/placement
    release_values: "{{ helm_release_values }}"
    create_namespace: true
    atomic: true
    timeout: 1m
