- ansible.builtin.template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
  register: keystone_conf

- ansible.builtin.template:
    src: adminrc.j2
    dest: /etc/adminrc

- name: init db
  ansible.builtin.shell: |
    mysql -e 'CREATE DATABASE IF NOT EXISTS keystone'

    /opt/keystone/bin/keystone-manage db_sync

    /opt/keystone/bin/keystone-manage fernet_setup --keystone-user nobody --keystone-group nobody
    /opt/keystone/bin/keystone-manage credential_setup --keystone-user nobody --keystone-group nobody

    /opt/keystone/bin/keystone-manage bootstrap --bootstrap-password "{{ keystone_admin_password }}" \
      --bootstrap-admin-url "http://{{ keystone_host }}:5000/v3/" \
      --bootstrap-internal-url "http://{{ keystone_host }}:5000/v3/" \
      --bootstrap-public-url "http://{{ keystone_host }}:5000/v3/" \
      --bootstrap-region-id "{{ keystone_region }}"

# - name: start keystone
#   ansible.builtin.shell: |
#     systemctl status keystone-public || systemd-run --unit keystone-public -- \
#       /opt/keystone/bin/keystone-wsgi-public --port 5001

- ansible.builtin.template:
    src: wsgi-keystone.conf.j2
    dest: /etc/httpd/conf.d/wsgi-keystone.conf
  register: wsgi_keystone_conf

# /usr/libexec/mod_auth_mellon/mellon_create_metadata.sh http://192.168.10.121:5000/mellon http://192.168.10.121:5000/v3/OS-FEDERATION/identity_providers/samltest/protocols/saml2/auth/mellon

- name: start keystone
  ansible.builtin.shell: |
    systemctl start httpd

- name: restart keystone
  when: keystone_conf.changed or wsgi_keystone_conf.changed
  ansible.builtin.shell: |
    systemctl restart httpd

- name: create user
  ansible.builtin.shell: |
    source /etc/adminrc

    timeout 5 bash -c 'until openstack token issue; do sleep 1; done'

    openstack project show service || openstack project create --domain default --description "Service Project" service
    openstack user show "{{ keystone_service_user }}" || openstack user create --domain default --password "{{ keystone_service_password }}" "{{ keystone_service_user }}"
    openstack role add --project service --user "{{ keystone_service_user }}" admin
