- name: Start mysql
  ansible.builtin.service:
    name: mysqld
    state: started

- name: Waiting for activating
  ansible.builtin.shell: |
    set -e
    NEXT_WAIT_TIME=0
    until mysql -e "show databases;" || [ $NEXT_WAIT_TIME -eq 4 ]; do
        sleep $((NEXT_WAIT_TIME++))
    done
  changed_when: false

- name: Create users
  loop: "{{ mysql_users }}"
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "*.*:ALL,GRANT"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Create databases
  loop: "{{ mysql_databases }}"
  community.mysql.mysql_db:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item }}"
    state: present
