docker:
  children:
    mysql:
    keystone:

mysql:
  hosts:
    ctl01:

memcached:
  hosts:
    ctl01:

rabbitmq:
  hosts:
    ctl01:

keystone:
  hosts:
    ctl01:

workstation:
  hosts:
    ansible:
