- name: Create images
  loop: "{{ osdata_images }}"
  shell: |
    source /etc/adminrc

    set +e
    image_show=$(openstack image show "{{ item.name }}"  2>&1)
    image_show_result=$?

    set -e
    if [ ${image_show_result} != 0 ]; then
      if echo "${image_show}" | grep "No Image found for {{ item.name }}$"; then
        rm -f /tmp/img
        wget {{ item.url }} -O /tmp/img

        openstack image create \
          --file /tmp/img \
          {{ item.options }} \
          {{ item.name }}

        rm -f /tmp/img
      else
        echo "Failed to openstack image show {{ item.name }}" >&2
        exit 1
      fi
    fi
