- include_role:
    name: openstack/bobcat/neutron
    tasks_from: config.yaml

- name: Put openvswitch_agent.ini
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
  register: openvswitch_agent_ini

- name: Put metadata_agent.ini
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/metadata_agent.ini
  register: metadata_agent_ini

- name: Put dhcp_agent_ini
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/dhcp_agent.ini
  register: dhcp_agent_ini

- name: Start neutron agents
  shell: |
    set -e

    export PATH=/opt/neutron/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    systemctl reset-failed neutron-openvswitch-agent || echo 'ignored'
    systemctl status neutron-openvswitch-agent || systemd-run \
      --unit neutron-server -- \
      {{ neutron_venv }}/bin/neutron-openvswitch-agent --log-file /var/log/neutron/neutron-openvswitch-agent.log \
      --config-file /etc/neutron/neutron.conf \
      --config-file /etc/neutron/plugins/ml2/ml2_conf.ini \
      --config-file /etc/neutron/plugins/ml2/openvswitch_agent.ini

- name: Restart neutron-openvswitch-agent
  when: neutron_conf.changed
    or neutron_ml2_conf.changed
    or openvswitch_agent_ini.changed
  service:
    name: neutron-openvswitch-agent
    state: restarted
