- include_tasks: config.yaml

- name: Sync DB
  shell: |
    set -e

    mysql -e 'CREATE DATABASE IF NOT EXISTS neutron'
    {{ neutron_venv }}/bin/neutron-db-manage --config-file /etc/neutron/neutron.conf \
      --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

- name: Start neutron
  shell: |
    set -e

    export PATH=/opt/neutron/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    systemctl reset-failed neutron-server || echo 'ignored'
    systemctl status neutron-server || systemd-run \
      --unit neutron-server -- \
      {{ neutron_venv }}/bin/neutron-server --log-file /var/log/neutron/neutron-server.log \
      --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini

- name: Restart neutron
  when: neutron_conf.changed
    or neutron_ml2_conf.changed
  shell: |
    set -e

    systemctl restart neutron-server

- name: Register neutron service
  shell: |
    set -e

    source /etc/adminrc
    service_list=$(openstack service list)
    if [[ ! $service_list =~ " neutron " ]]; then
      openstack service create --name neutron --description "OpenStack Networking" network
      openstack endpoint create --region "{{ neutron_keystone_region }}" network public   "http://{{ neutron_keystone_host }}:9696"
      openstack endpoint create --region "{{ neutron_keystone_region }}" network internal "http://{{ neutron_keystone_host }}:9696"
      openstack endpoint create --region "{{ neutron_keystone_region }}" network admin    "http://{{ neutron_keystone_host }}:9696"
    fi
