- name: Install requirement packages
  ansible.builtin.dnf:
    name:
      - yum-utils
      - epel-release

- name: Add repo
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  changed_when: false

- name: Install docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker
