- name: Install venv
  shell: |
    set -e

    python3 -m venv {{ glance_venv }} --system-site-packages
    {{ glance_venv }}/bin/pip install pip --upgrade
    mkdir -p /var/log/glance
    mkdir -p /etc/glance
    mkdir -p /var/lib/glance/images/

- include_role:
    name: openstack/bobcat/common
    tasks_from: upper_constraints.yaml
  vars:
    dir: "{{ glance_venv }}"

- name: Put requirements.txt
  copy:
    src: files/requirements.txt
    dest: "{{ glance_venv }}/requirements.txt"

- name: Install glance
  shell: |
    set -e

    mkdir -p {{ glance_venv }}/src
    cd {{ glance_venv }}/src
    test -e glance || git clone {{ glance_git_repo }} -b {{ glance_git_branch }}

    cd glance
    {{ glance_venv }}/bin/pip install . \
      -r requirements.txt \
      -r {{ glance_venv }}/requirements.txt \
      -c {{ glance_venv }}/upper-constraints.txt

    cp etc/glance-api-paste.ini /etc/glance/
