- name: Put glance-api.conf
  ansible.builtin.template:
    src: glance-api.conf.j2
    dest: "/etc/glance/glance-api.conf"
    mode: "600"
  notify:
    - Restart glance-api

- name: Sync DB
  ansible.builtin.command: "{{ glance_venv }}/bin/glance-manage db_sync"
  changed_when: false

- name: Start glance
  ansible.builtin.shell: |
    set -e

    systemctl reset-failed glance-api || echo 'ignored'
    systemctl status glance-api || systemd-run \
      --unit glance-api -- \
      {{ glance_venv }}/bin/glance-api --config-file /etc/glance/glance-api.conf
  changed_when: false
